# Generated by Django 4.0.6 on 2022-08-11 13:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0002_lessontimetable_lesson_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessontimetable',
            name='lesson_date',
        ),
        migrations.RemoveField(
            model_name='lessontimetable',
            name='lesson_time_end',
        ),
        migrations.RemoveField(
            model_name='lessontimetable',
            name='lesson_time_start',
        ),
        migrations.RemoveField(
            model_name='possibletimetable',
            name='lesson_date',
        ),
        migrations.RemoveField(
            model_name='possibletimetable',
            name='lesson_time_end',
        ),
        migrations.RemoveField(
            model_name='possibletimetable',
            name='lesson_time_start',
        ),
        migrations.AddField(
            model_name='lessontimetable',
            name='end_lesson_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 13, 29, 14, 842840, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='lessontimetable',
            name='start_lesson_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 13, 29, 14, 842825, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='possibletimetable',
            name='end_lesson_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 13, 29, 14, 842454, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='possibletimetable',
            name='start_lesson_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 13, 29, 14, 842428, tzinfo=utc)),
        ),
    ]
