# Generated by Django 4.0.6 on 2022-08-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0003_remove_lessontimetable_lesson_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontimetable',
            name='end_lesson_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lessontimetable',
            name='start_lesson_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='possibletimetable',
            name='end_lesson_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='possibletimetable',
            name='start_lesson_datetime',
            field=models.DateTimeField(),
        ),
    ]
